# Generated by Django 5.2 on 2025-04-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='indoor_people_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='outdoor_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='party_type',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=20, null=True),
        ),
    ]
